SELECT COUNT(ID) FISH_COUNT, MAX(IFNULL(LENGTH,10)) MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE 
HAVING AVG(IFNULL(LENGTH,10))>=33
ORDER BY FISH_TYPE;

null인 컬럼의 default를 정해줄 수 있는 
IFNULL() 메서드를 기억
