SELECT DE.DEPT_ID, DE.DEPT_NAME_EN, ROUND(AVG(EM.SAL)) AVG_SAL
FROM HR_DEPARTMENT DE, HR_EMPLOYEES EM
WHERE DE.DEPT_ID=EM.DEPT_ID
GROUP BY DE.DEPT_ID
ORDER BY AVG_SAL DESC;

컬럼들이 어느 소속인지를 지정해주면서 진행하자
